// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gcal/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/gcal/client.go -destination=internal/testutil/mocks/mock_gcal.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gcal "github.com/0utl1er-tech/phox-customer/internal/gcal"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockClient) CreateEvent(ctx context.Context, userID string, in gcal.EventInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, userID, in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockClientMockRecorder) CreateEvent(ctx, userID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockClient)(nil).CreateEvent), ctx, userID, in)
}

// DeleteEvent mocks base method.
func (m *MockClient) DeleteEvent(ctx context.Context, userID, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockClientMockRecorder) DeleteEvent(ctx, userID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockClient)(nil).DeleteEvent), ctx, userID, eventID)
}

// PatchEvent mocks base method.
func (m *MockClient) PatchEvent(ctx context.Context, userID, eventID string, in gcal.EventInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchEvent", ctx, userID, eventID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchEvent indicates an expected call of PatchEvent.
func (mr *MockClientMockRecorder) PatchEvent(ctx, userID, eventID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchEvent", reflect.TypeOf((*MockClient)(nil).PatchEvent), ctx, userID, eventID, in)
}
