// Code generated by MockGen. DO NOT EDIT.
// Source: gen/sqlc/querier.go
//
// Generated by this command:
//
//	mockgen -source=gen/sqlc/querier.go -destination=internal/testutil/mocks/mock_querier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/0utl1er-tech/phox-customer/gen/sqlc"
	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CheckUserAccessToBook mocks base method.
func (m *MockQuerier) CheckUserAccessToBook(ctx context.Context, arg sqlc.CheckUserAccessToBookParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserAccessToBook", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserAccessToBook indicates an expected call of CheckUserAccessToBook.
func (mr *MockQuerierMockRecorder) CheckUserAccessToBook(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserAccessToBook", reflect.TypeOf((*MockQuerier)(nil).CheckUserAccessToBook), ctx, arg)
}

// CheckUserRoleForBook mocks base method.
func (m *MockQuerier) CheckUserRoleForBook(ctx context.Context, arg sqlc.CheckUserRoleForBookParams) (sqlc.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserRoleForBook", ctx, arg)
	ret0, _ := ret[0].(sqlc.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserRoleForBook indicates an expected call of CheckUserRoleForBook.
func (mr *MockQuerierMockRecorder) CheckUserRoleForBook(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserRoleForBook", reflect.TypeOf((*MockQuerier)(nil).CheckUserRoleForBook), ctx, arg)
}

// ClearRedialGcalSync mocks base method.
func (m *MockQuerier) ClearRedialGcalSync(ctx context.Context, id uuid.UUID) (sqlc.Redial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRedialGcalSync", ctx, id)
	ret0, _ := ret[0].(sqlc.Redial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearRedialGcalSync indicates an expected call of ClearRedialGcalSync.
func (mr *MockQuerierMockRecorder) ClearRedialGcalSync(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRedialGcalSync", reflect.TypeOf((*MockQuerier)(nil).ClearRedialGcalSync), ctx, id)
}

// CreateActivity mocks base method.
func (m *MockQuerier) CreateActivity(ctx context.Context, arg sqlc.CreateActivityParams) (sqlc.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivity", ctx, arg)
	ret0, _ := ret[0].(sqlc.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActivity indicates an expected call of CreateActivity.
func (mr *MockQuerierMockRecorder) CreateActivity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivity", reflect.TypeOf((*MockQuerier)(nil).CreateActivity), ctx, arg)
}

// CreateBook mocks base method.
func (m *MockQuerier) CreateBook(ctx context.Context, arg sqlc.CreateBookParams) (sqlc.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBook", ctx, arg)
	ret0, _ := ret[0].(sqlc.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBook indicates an expected call of CreateBook.
func (mr *MockQuerierMockRecorder) CreateBook(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBook", reflect.TypeOf((*MockQuerier)(nil).CreateBook), ctx, arg)
}

// CreateCompany mocks base method.
func (m *MockQuerier) CreateCompany(ctx context.Context, arg sqlc.CreateCompanyParams) (sqlc.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompany", ctx, arg)
	ret0, _ := ret[0].(sqlc.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompany indicates an expected call of CreateCompany.
func (mr *MockQuerierMockRecorder) CreateCompany(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompany", reflect.TypeOf((*MockQuerier)(nil).CreateCompany), ctx, arg)
}

// CreateContact mocks base method.
func (m *MockQuerier) CreateContact(ctx context.Context, arg sqlc.CreateContactParams) (sqlc.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContact", ctx, arg)
	ret0, _ := ret[0].(sqlc.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContact indicates an expected call of CreateContact.
func (mr *MockQuerierMockRecorder) CreateContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContact", reflect.TypeOf((*MockQuerier)(nil).CreateContact), ctx, arg)
}

// CreateCustomer mocks base method.
func (m *MockQuerier) CreateCustomer(ctx context.Context, arg sqlc.CreateCustomerParams) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, arg)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockQuerierMockRecorder) CreateCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockQuerier)(nil).CreateCustomer), ctx, arg)
}

// CreateMailTemplate mocks base method.
func (m *MockQuerier) CreateMailTemplate(ctx context.Context, arg sqlc.CreateMailTemplateParams) (sqlc.MailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMailTemplate", ctx, arg)
	ret0, _ := ret[0].(sqlc.MailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMailTemplate indicates an expected call of CreateMailTemplate.
func (mr *MockQuerierMockRecorder) CreateMailTemplate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMailTemplate", reflect.TypeOf((*MockQuerier)(nil).CreateMailTemplate), ctx, arg)
}

// CreatePermit mocks base method.
func (m *MockQuerier) CreatePermit(ctx context.Context, arg sqlc.CreatePermitParams) (sqlc.Permit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermit", ctx, arg)
	ret0, _ := ret[0].(sqlc.Permit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermit indicates an expected call of CreatePermit.
func (mr *MockQuerierMockRecorder) CreatePermit(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermit", reflect.TypeOf((*MockQuerier)(nil).CreatePermit), ctx, arg)
}

// CreateRedial mocks base method.
func (m *MockQuerier) CreateRedial(ctx context.Context, arg sqlc.CreateRedialParams) (sqlc.Redial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRedial", ctx, arg)
	ret0, _ := ret[0].(sqlc.Redial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRedial indicates an expected call of CreateRedial.
func (mr *MockQuerierMockRecorder) CreateRedial(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRedial", reflect.TypeOf((*MockQuerier)(nil).CreateRedial), ctx, arg)
}

// CreateStatus mocks base method.
func (m *MockQuerier) CreateStatus(ctx context.Context, arg sqlc.CreateStatusParams) (sqlc.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStatus indicates an expected call of CreateStatus.
func (mr *MockQuerierMockRecorder) CreateStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStatus", reflect.TypeOf((*MockQuerier)(nil).CreateStatus), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// DeleteActivity mocks base method.
func (m *MockQuerier) DeleteActivity(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActivity indicates an expected call of DeleteActivity.
func (mr *MockQuerierMockRecorder) DeleteActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActivity", reflect.TypeOf((*MockQuerier)(nil).DeleteActivity), ctx, id)
}

// DeleteBook mocks base method.
func (m *MockQuerier) DeleteBook(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBook", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBook indicates an expected call of DeleteBook.
func (mr *MockQuerierMockRecorder) DeleteBook(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBook", reflect.TypeOf((*MockQuerier)(nil).DeleteBook), ctx, id)
}

// DeleteCompany mocks base method.
func (m *MockQuerier) DeleteCompany(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompany", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCompany indicates an expected call of DeleteCompany.
func (mr *MockQuerierMockRecorder) DeleteCompany(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompany", reflect.TypeOf((*MockQuerier)(nil).DeleteCompany), ctx, id)
}

// DeleteContact mocks base method.
func (m *MockQuerier) DeleteContact(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContact", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContact indicates an expected call of DeleteContact.
func (mr *MockQuerierMockRecorder) DeleteContact(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContact", reflect.TypeOf((*MockQuerier)(nil).DeleteContact), ctx, id)
}

// DeleteCustomer mocks base method.
func (m *MockQuerier) DeleteCustomer(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer.
func (mr *MockQuerierMockRecorder) DeleteCustomer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockQuerier)(nil).DeleteCustomer), ctx, id)
}

// DeleteMailTemplate mocks base method.
func (m *MockQuerier) DeleteMailTemplate(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMailTemplate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMailTemplate indicates an expected call of DeleteMailTemplate.
func (mr *MockQuerierMockRecorder) DeleteMailTemplate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMailTemplate", reflect.TypeOf((*MockQuerier)(nil).DeleteMailTemplate), ctx, id)
}

// DeletePermit mocks base method.
func (m *MockQuerier) DeletePermit(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermit", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermit indicates an expected call of DeletePermit.
func (mr *MockQuerierMockRecorder) DeletePermit(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermit", reflect.TypeOf((*MockQuerier)(nil).DeletePermit), ctx, id)
}

// DeleteRedial mocks base method.
func (m *MockQuerier) DeleteRedial(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRedial", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRedial indicates an expected call of DeleteRedial.
func (mr *MockQuerierMockRecorder) DeleteRedial(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRedial", reflect.TypeOf((*MockQuerier)(nil).DeleteRedial), ctx, id)
}

// DeleteStatus mocks base method.
func (m *MockQuerier) DeleteStatus(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStatus", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStatus indicates an expected call of DeleteStatus.
func (mr *MockQuerierMockRecorder) DeleteStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStatus", reflect.TypeOf((*MockQuerier)(nil).DeleteStatus), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockQuerier) DeleteUser(ctx context.Context, id string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockQuerierMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockQuerier)(nil).DeleteUser), ctx, id)
}

// DeleteUserGoogleToken mocks base method.
func (m *MockQuerier) DeleteUserGoogleToken(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserGoogleToken", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserGoogleToken indicates an expected call of DeleteUserGoogleToken.
func (mr *MockQuerierMockRecorder) DeleteUserGoogleToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserGoogleToken", reflect.TypeOf((*MockQuerier)(nil).DeleteUserGoogleToken), ctx, userID)
}

// DeleteUserICalFeed mocks base method.
func (m *MockQuerier) DeleteUserICalFeed(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserICalFeed", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserICalFeed indicates an expected call of DeleteUserICalFeed.
func (mr *MockQuerierMockRecorder) DeleteUserICalFeed(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserICalFeed", reflect.TypeOf((*MockQuerier)(nil).DeleteUserICalFeed), ctx, userID)
}

// FindCustomerByEmail mocks base method.
func (m *MockQuerier) FindCustomerByEmail(ctx context.Context, mail string) (sqlc.FindCustomerByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCustomerByEmail", ctx, mail)
	ret0, _ := ret[0].(sqlc.FindCustomerByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCustomerByEmail indicates an expected call of FindCustomerByEmail.
func (mr *MockQuerierMockRecorder) FindCustomerByEmail(ctx, mail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCustomerByEmail", reflect.TypeOf((*MockQuerier)(nil).FindCustomerByEmail), ctx, mail)
}

// FindUnsyncedRedialsByUser mocks base method.
func (m *MockQuerier) FindUnsyncedRedialsByUser(ctx context.Context, userID string) ([]sqlc.Redial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUnsyncedRedialsByUser", ctx, userID)
	ret0, _ := ret[0].([]sqlc.Redial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUnsyncedRedialsByUser indicates an expected call of FindUnsyncedRedialsByUser.
func (mr *MockQuerierMockRecorder) FindUnsyncedRedialsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUnsyncedRedialsByUser", reflect.TypeOf((*MockQuerier)(nil).FindUnsyncedRedialsByUser), ctx, userID)
}

// FindUserICalFeedByToken mocks base method.
func (m *MockQuerier) FindUserICalFeedByToken(ctx context.Context, token string) (sqlc.UserICalFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserICalFeedByToken", ctx, token)
	ret0, _ := ret[0].(sqlc.UserICalFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserICalFeedByToken indicates an expected call of FindUserICalFeedByToken.
func (mr *MockQuerierMockRecorder) FindUserICalFeedByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserICalFeedByToken", reflect.TypeOf((*MockQuerier)(nil).FindUserICalFeedByToken), ctx, token)
}

// GetActivity mocks base method.
func (m *MockQuerier) GetActivity(ctx context.Context, id uuid.UUID) (sqlc.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivity", ctx, id)
	ret0, _ := ret[0].(sqlc.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivity indicates an expected call of GetActivity.
func (mr *MockQuerierMockRecorder) GetActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivity", reflect.TypeOf((*MockQuerier)(nil).GetActivity), ctx, id)
}

// GetActivityByMessageID mocks base method.
func (m *MockQuerier) GetActivityByMessageID(ctx context.Context, messageID pgtype.Text) (sqlc.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityByMessageID", ctx, messageID)
	ret0, _ := ret[0].(sqlc.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityByMessageID indicates an expected call of GetActivityByMessageID.
func (mr *MockQuerierMockRecorder) GetActivityByMessageID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityByMessageID", reflect.TypeOf((*MockQuerier)(nil).GetActivityByMessageID), ctx, messageID)
}

// GetBookByIDAndUserID mocks base method.
func (m *MockQuerier) GetBookByIDAndUserID(ctx context.Context, arg sqlc.GetBookByIDAndUserIDParams) (sqlc.GetBookByIDAndUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookByIDAndUserID", ctx, arg)
	ret0, _ := ret[0].(sqlc.GetBookByIDAndUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookByIDAndUserID indicates an expected call of GetBookByIDAndUserID.
func (mr *MockQuerierMockRecorder) GetBookByIDAndUserID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookByIDAndUserID", reflect.TypeOf((*MockQuerier)(nil).GetBookByIDAndUserID), ctx, arg)
}

// GetBooksByUserID mocks base method.
func (m *MockQuerier) GetBooksByUserID(ctx context.Context, userID string) ([]sqlc.GetBooksByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooksByUserID", ctx, userID)
	ret0, _ := ret[0].([]sqlc.GetBooksByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooksByUserID indicates an expected call of GetBooksByUserID.
func (mr *MockQuerierMockRecorder) GetBooksByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooksByUserID", reflect.TypeOf((*MockQuerier)(nil).GetBooksByUserID), ctx, userID)
}

// GetCompany mocks base method.
func (m *MockQuerier) GetCompany(ctx context.Context, id uuid.UUID) (sqlc.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompany", ctx, id)
	ret0, _ := ret[0].(sqlc.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompany indicates an expected call of GetCompany.
func (mr *MockQuerierMockRecorder) GetCompany(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompany", reflect.TypeOf((*MockQuerier)(nil).GetCompany), ctx, id)
}

// GetContact mocks base method.
func (m *MockQuerier) GetContact(ctx context.Context, id uuid.UUID) (sqlc.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContact", ctx, id)
	ret0, _ := ret[0].(sqlc.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContact indicates an expected call of GetContact.
func (mr *MockQuerierMockRecorder) GetContact(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContact", reflect.TypeOf((*MockQuerier)(nil).GetContact), ctx, id)
}

// GetCustomer mocks base method.
func (m *MockQuerier) GetCustomer(ctx context.Context, id uuid.UUID) (sqlc.GetCustomerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomer", ctx, id)
	ret0, _ := ret[0].(sqlc.GetCustomerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockQuerierMockRecorder) GetCustomer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockQuerier)(nil).GetCustomer), ctx, id)
}

// GetCustomerByBookId mocks base method.
func (m *MockQuerier) GetCustomerByBookId(ctx context.Context, bookID uuid.UUID) (sqlc.GetCustomerByBookIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByBookId", ctx, bookID)
	ret0, _ := ret[0].(sqlc.GetCustomerByBookIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByBookId indicates an expected call of GetCustomerByBookId.
func (mr *MockQuerierMockRecorder) GetCustomerByBookId(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByBookId", reflect.TypeOf((*MockQuerier)(nil).GetCustomerByBookId), ctx, bookID)
}

// GetCustomerCount mocks base method.
func (m *MockQuerier) GetCustomerCount(ctx context.Context, bookID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerCount", ctx, bookID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerCount indicates an expected call of GetCustomerCount.
func (mr *MockQuerierMockRecorder) GetCustomerCount(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerCount", reflect.TypeOf((*MockQuerier)(nil).GetCustomerCount), ctx, bookID)
}

// GetCustomerCountByAddress mocks base method.
func (m *MockQuerier) GetCustomerCountByAddress(ctx context.Context, arg sqlc.GetCustomerCountByAddressParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerCountByAddress", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerCountByAddress indicates an expected call of GetCustomerCountByAddress.
func (mr *MockQuerierMockRecorder) GetCustomerCountByAddress(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerCountByAddress", reflect.TypeOf((*MockQuerier)(nil).GetCustomerCountByAddress), ctx, arg)
}

// GetCustomerCountByCategory mocks base method.
func (m *MockQuerier) GetCustomerCountByCategory(ctx context.Context, arg sqlc.GetCustomerCountByCategoryParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerCountByCategory", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerCountByCategory indicates an expected call of GetCustomerCountByCategory.
func (mr *MockQuerierMockRecorder) GetCustomerCountByCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerCountByCategory", reflect.TypeOf((*MockQuerier)(nil).GetCustomerCountByCategory), ctx, arg)
}

// GetCustomerCountByCorporation mocks base method.
func (m *MockQuerier) GetCustomerCountByCorporation(ctx context.Context, arg sqlc.GetCustomerCountByCorporationParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerCountByCorporation", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerCountByCorporation indicates an expected call of GetCustomerCountByCorporation.
func (mr *MockQuerierMockRecorder) GetCustomerCountByCorporation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerCountByCorporation", reflect.TypeOf((*MockQuerier)(nil).GetCustomerCountByCorporation), ctx, arg)
}

// GetCustomerCountByDate mocks base method.
func (m *MockQuerier) GetCustomerCountByDate(ctx context.Context, arg sqlc.GetCustomerCountByDateParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerCountByDate", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerCountByDate indicates an expected call of GetCustomerCountByDate.
func (mr *MockQuerierMockRecorder) GetCustomerCountByDate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerCountByDate", reflect.TypeOf((*MockQuerier)(nil).GetCustomerCountByDate), ctx, arg)
}

// GetDefaultStatusByBookID mocks base method.
func (m *MockQuerier) GetDefaultStatusByBookID(ctx context.Context, bookID uuid.UUID) (sqlc.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultStatusByBookID", ctx, bookID)
	ret0, _ := ret[0].(sqlc.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultStatusByBookID indicates an expected call of GetDefaultStatusByBookID.
func (mr *MockQuerierMockRecorder) GetDefaultStatusByBookID(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultStatusByBookID", reflect.TypeOf((*MockQuerier)(nil).GetDefaultStatusByBookID), ctx, bookID)
}

// GetMailTemplate mocks base method.
func (m *MockQuerier) GetMailTemplate(ctx context.Context, id uuid.UUID) (sqlc.MailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMailTemplate", ctx, id)
	ret0, _ := ret[0].(sqlc.MailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMailTemplate indicates an expected call of GetMailTemplate.
func (mr *MockQuerierMockRecorder) GetMailTemplate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMailTemplate", reflect.TypeOf((*MockQuerier)(nil).GetMailTemplate), ctx, id)
}

// GetMaxStatusPriority mocks base method.
func (m *MockQuerier) GetMaxStatusPriority(ctx context.Context, bookID uuid.UUID) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxStatusPriority", ctx, bookID)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxStatusPriority indicates an expected call of GetMaxStatusPriority.
func (mr *MockQuerierMockRecorder) GetMaxStatusPriority(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxStatusPriority", reflect.TypeOf((*MockQuerier)(nil).GetMaxStatusPriority), ctx, bookID)
}

// GetPermit mocks base method.
func (m *MockQuerier) GetPermit(ctx context.Context, id uuid.UUID) (sqlc.Permit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermit", ctx, id)
	ret0, _ := ret[0].(sqlc.Permit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermit indicates an expected call of GetPermit.
func (mr *MockQuerierMockRecorder) GetPermit(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermit", reflect.TypeOf((*MockQuerier)(nil).GetPermit), ctx, id)
}

// GetPermitByBookIDAndUserID mocks base method.
func (m *MockQuerier) GetPermitByBookIDAndUserID(ctx context.Context, arg sqlc.GetPermitByBookIDAndUserIDParams) (sqlc.Permit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermitByBookIDAndUserID", ctx, arg)
	ret0, _ := ret[0].(sqlc.Permit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermitByBookIDAndUserID indicates an expected call of GetPermitByBookIDAndUserID.
func (mr *MockQuerierMockRecorder) GetPermitByBookIDAndUserID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermitByBookIDAndUserID", reflect.TypeOf((*MockQuerier)(nil).GetPermitByBookIDAndUserID), ctx, arg)
}

// GetPermitsByUserID mocks base method.
func (m *MockQuerier) GetPermitsByUserID(ctx context.Context, userID string) ([]sqlc.Permit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermitsByUserID", ctx, userID)
	ret0, _ := ret[0].([]sqlc.Permit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermitsByUserID indicates an expected call of GetPermitsByUserID.
func (mr *MockQuerierMockRecorder) GetPermitsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermitsByUserID", reflect.TypeOf((*MockQuerier)(nil).GetPermitsByUserID), ctx, userID)
}

// GetRedial mocks base method.
func (m *MockQuerier) GetRedial(ctx context.Context, id uuid.UUID) (sqlc.Redial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedial", ctx, id)
	ret0, _ := ret[0].(sqlc.Redial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRedial indicates an expected call of GetRedial.
func (mr *MockQuerierMockRecorder) GetRedial(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedial", reflect.TypeOf((*MockQuerier)(nil).GetRedial), ctx, id)
}

// GetStatus mocks base method.
func (m *MockQuerier) GetStatus(ctx context.Context, id uuid.UUID) (sqlc.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, id)
	ret0, _ := ret[0].(sqlc.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockQuerierMockRecorder) GetStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockQuerier)(nil).GetStatus), ctx, id)
}

// GetUser mocks base method.
func (m *MockQuerier) GetUser(ctx context.Context, id string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockQuerierMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockQuerier)(nil).GetUser), ctx, id)
}

// GetUserGoogleToken mocks base method.
func (m *MockQuerier) GetUserGoogleToken(ctx context.Context, userID string) (sqlc.UserGoogleToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGoogleToken", ctx, userID)
	ret0, _ := ret[0].(sqlc.UserGoogleToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserGoogleToken indicates an expected call of GetUserGoogleToken.
func (mr *MockQuerierMockRecorder) GetUserGoogleToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGoogleToken", reflect.TypeOf((*MockQuerier)(nil).GetUserGoogleToken), ctx, userID)
}

// GetUserICalFeed mocks base method.
func (m *MockQuerier) GetUserICalFeed(ctx context.Context, userID string) (sqlc.UserICalFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserICalFeed", ctx, userID)
	ret0, _ := ret[0].(sqlc.UserICalFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserICalFeed indicates an expected call of GetUserICalFeed.
func (mr *MockQuerierMockRecorder) GetUserICalFeed(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserICalFeed", reflect.TypeOf((*MockQuerier)(nil).GetUserICalFeed), ctx, userID)
}

// ListActivitiesByCustomerID mocks base method.
func (m *MockQuerier) ListActivitiesByCustomerID(ctx context.Context, arg sqlc.ListActivitiesByCustomerIDParams) ([]sqlc.ListActivitiesByCustomerIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivitiesByCustomerID", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ListActivitiesByCustomerIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActivitiesByCustomerID indicates an expected call of ListActivitiesByCustomerID.
func (mr *MockQuerierMockRecorder) ListActivitiesByCustomerID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivitiesByCustomerID", reflect.TypeOf((*MockQuerier)(nil).ListActivitiesByCustomerID), ctx, arg)
}

// ListAllContacts mocks base method.
func (m *MockQuerier) ListAllContacts(ctx context.Context, arg sqlc.ListAllContactsParams) ([]sqlc.ListAllContactsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllContacts", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ListAllContactsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllContacts indicates an expected call of ListAllContacts.
func (mr *MockQuerierMockRecorder) ListAllContacts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllContacts", reflect.TypeOf((*MockQuerier)(nil).ListAllContacts), ctx, arg)
}

// ListAllCustomers mocks base method.
func (m *MockQuerier) ListAllCustomers(ctx context.Context) ([]sqlc.ListAllCustomersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllCustomers", ctx)
	ret0, _ := ret[0].([]sqlc.ListAllCustomersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllCustomers indicates an expected call of ListAllCustomers.
func (mr *MockQuerierMockRecorder) ListAllCustomers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllCustomers", reflect.TypeOf((*MockQuerier)(nil).ListAllCustomers), ctx)
}

// ListCompanies mocks base method.
func (m *MockQuerier) ListCompanies(ctx context.Context) ([]sqlc.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompanies", ctx)
	ret0, _ := ret[0].([]sqlc.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompanies indicates an expected call of ListCompanies.
func (mr *MockQuerierMockRecorder) ListCompanies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompanies", reflect.TypeOf((*MockQuerier)(nil).ListCompanies), ctx)
}

// ListContacts mocks base method.
func (m *MockQuerier) ListContacts(ctx context.Context, customerID uuid.UUID) ([]sqlc.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContacts", ctx, customerID)
	ret0, _ := ret[0].([]sqlc.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContacts indicates an expected call of ListContacts.
func (mr *MockQuerierMockRecorder) ListContacts(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContacts", reflect.TypeOf((*MockQuerier)(nil).ListContacts), ctx, customerID)
}

// ListCustomers mocks base method.
func (m *MockQuerier) ListCustomers(ctx context.Context, arg sqlc.ListCustomersParams) ([]sqlc.ListCustomersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ListCustomersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomers indicates an expected call of ListCustomers.
func (mr *MockQuerierMockRecorder) ListCustomers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockQuerier)(nil).ListCustomers), ctx, arg)
}

// ListMailTemplatesByBook mocks base method.
func (m *MockQuerier) ListMailTemplatesByBook(ctx context.Context, bookID uuid.UUID) ([]sqlc.MailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMailTemplatesByBook", ctx, bookID)
	ret0, _ := ret[0].([]sqlc.MailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMailTemplatesByBook indicates an expected call of ListMailTemplatesByBook.
func (mr *MockQuerierMockRecorder) ListMailTemplatesByBook(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMailTemplatesByBook", reflect.TypeOf((*MockQuerier)(nil).ListMailTemplatesByBook), ctx, bookID)
}

// ListPermits mocks base method.
func (m *MockQuerier) ListPermits(ctx context.Context, bookID uuid.UUID) ([]sqlc.Permit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermits", ctx, bookID)
	ret0, _ := ret[0].([]sqlc.Permit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermits indicates an expected call of ListPermits.
func (mr *MockQuerierMockRecorder) ListPermits(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermits", reflect.TypeOf((*MockQuerier)(nil).ListPermits), ctx, bookID)
}

// ListPermitsWithUserInfo mocks base method.
func (m *MockQuerier) ListPermitsWithUserInfo(ctx context.Context, bookID uuid.UUID) ([]sqlc.ListPermitsWithUserInfoRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermitsWithUserInfo", ctx, bookID)
	ret0, _ := ret[0].([]sqlc.ListPermitsWithUserInfoRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermitsWithUserInfo indicates an expected call of ListPermitsWithUserInfo.
func (mr *MockQuerierMockRecorder) ListPermitsWithUserInfo(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermitsWithUserInfo", reflect.TypeOf((*MockQuerier)(nil).ListPermitsWithUserInfo), ctx, bookID)
}

// ListRedialsByCustomer mocks base method.
func (m *MockQuerier) ListRedialsByCustomer(ctx context.Context, customerID uuid.UUID) ([]sqlc.Redial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRedialsByCustomer", ctx, customerID)
	ret0, _ := ret[0].([]sqlc.Redial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRedialsByCustomer indicates an expected call of ListRedialsByCustomer.
func (mr *MockQuerierMockRecorder) ListRedialsByCustomer(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRedialsByCustomer", reflect.TypeOf((*MockQuerier)(nil).ListRedialsByCustomer), ctx, customerID)
}

// ListRedialsByUserWithCustomer mocks base method.
func (m *MockQuerier) ListRedialsByUserWithCustomer(ctx context.Context, arg sqlc.ListRedialsByUserWithCustomerParams) ([]sqlc.ListRedialsByUserWithCustomerRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRedialsByUserWithCustomer", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ListRedialsByUserWithCustomerRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRedialsByUserWithCustomer indicates an expected call of ListRedialsByUserWithCustomer.
func (mr *MockQuerierMockRecorder) ListRedialsByUserWithCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRedialsByUserWithCustomer", reflect.TypeOf((*MockQuerier)(nil).ListRedialsByUserWithCustomer), ctx, arg)
}

// ListStatusesByBookID mocks base method.
func (m *MockQuerier) ListStatusesByBookID(ctx context.Context, bookID uuid.UUID) ([]sqlc.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStatusesByBookID", ctx, bookID)
	ret0, _ := ret[0].([]sqlc.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStatusesByBookID indicates an expected call of ListStatusesByBookID.
func (mr *MockQuerierMockRecorder) ListStatusesByBookID(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStatusesByBookID", reflect.TypeOf((*MockQuerier)(nil).ListStatusesByBookID), ctx, bookID)
}

// ListUsers mocks base method.
func (m *MockQuerier) ListUsers(ctx context.Context) ([]sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockQuerierMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockQuerier)(nil).ListUsers), ctx)
}

// ListUsersByCompany mocks base method.
func (m *MockQuerier) ListUsersByCompany(ctx context.Context, companyID uuid.UUID) ([]sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersByCompany", ctx, companyID)
	ret0, _ := ret[0].([]sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersByCompany indicates an expected call of ListUsersByCompany.
func (mr *MockQuerierMockRecorder) ListUsersByCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersByCompany", reflect.TypeOf((*MockQuerier)(nil).ListUsersByCompany), ctx, companyID)
}

// SetRedialGcalSynced mocks base method.
func (m *MockQuerier) SetRedialGcalSynced(ctx context.Context, arg sqlc.SetRedialGcalSyncedParams) (sqlc.Redial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRedialGcalSynced", ctx, arg)
	ret0, _ := ret[0].(sqlc.Redial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRedialGcalSynced indicates an expected call of SetRedialGcalSynced.
func (mr *MockQuerierMockRecorder) SetRedialGcalSynced(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRedialGcalSynced", reflect.TypeOf((*MockQuerier)(nil).SetRedialGcalSynced), ctx, arg)
}

// UpdateActivityStatus mocks base method.
func (m *MockQuerier) UpdateActivityStatus(ctx context.Context, arg sqlc.UpdateActivityStatusParams) (sqlc.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivityStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateActivityStatus indicates an expected call of UpdateActivityStatus.
func (mr *MockQuerierMockRecorder) UpdateActivityStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivityStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateActivityStatus), ctx, arg)
}

// UpdateBook mocks base method.
func (m *MockQuerier) UpdateBook(ctx context.Context, arg sqlc.UpdateBookParams) (sqlc.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", ctx, arg)
	ret0, _ := ret[0].(sqlc.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockQuerierMockRecorder) UpdateBook(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockQuerier)(nil).UpdateBook), ctx, arg)
}

// UpdateCompany mocks base method.
func (m *MockQuerier) UpdateCompany(ctx context.Context, arg sqlc.UpdateCompanyParams) (sqlc.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompany", ctx, arg)
	ret0, _ := ret[0].(sqlc.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCompany indicates an expected call of UpdateCompany.
func (mr *MockQuerierMockRecorder) UpdateCompany(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompany", reflect.TypeOf((*MockQuerier)(nil).UpdateCompany), ctx, arg)
}

// UpdateContact mocks base method.
func (m *MockQuerier) UpdateContact(ctx context.Context, arg sqlc.UpdateContactParams) (sqlc.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContact", ctx, arg)
	ret0, _ := ret[0].(sqlc.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContact indicates an expected call of UpdateContact.
func (mr *MockQuerierMockRecorder) UpdateContact(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContact", reflect.TypeOf((*MockQuerier)(nil).UpdateContact), ctx, arg)
}

// UpdateCustomer mocks base method.
func (m *MockQuerier) UpdateCustomer(ctx context.Context, arg sqlc.UpdateCustomerParams) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", ctx, arg)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomer indicates an expected call of UpdateCustomer.
func (mr *MockQuerierMockRecorder) UpdateCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockQuerier)(nil).UpdateCustomer), ctx, arg)
}

// UpdateMailTemplate mocks base method.
func (m *MockQuerier) UpdateMailTemplate(ctx context.Context, arg sqlc.UpdateMailTemplateParams) (sqlc.MailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMailTemplate", ctx, arg)
	ret0, _ := ret[0].(sqlc.MailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMailTemplate indicates an expected call of UpdateMailTemplate.
func (mr *MockQuerierMockRecorder) UpdateMailTemplate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMailTemplate", reflect.TypeOf((*MockQuerier)(nil).UpdateMailTemplate), ctx, arg)
}

// UpdatePermit mocks base method.
func (m *MockQuerier) UpdatePermit(ctx context.Context, arg sqlc.UpdatePermitParams) (sqlc.Permit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermit", ctx, arg)
	ret0, _ := ret[0].(sqlc.Permit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePermit indicates an expected call of UpdatePermit.
func (mr *MockQuerierMockRecorder) UpdatePermit(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermit", reflect.TypeOf((*MockQuerier)(nil).UpdatePermit), ctx, arg)
}

// UpdateRedial mocks base method.
func (m *MockQuerier) UpdateRedial(ctx context.Context, arg sqlc.UpdateRedialParams) (sqlc.Redial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRedial", ctx, arg)
	ret0, _ := ret[0].(sqlc.Redial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRedial indicates an expected call of UpdateRedial.
func (mr *MockQuerierMockRecorder) UpdateRedial(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRedial", reflect.TypeOf((*MockQuerier)(nil).UpdateRedial), ctx, arg)
}

// UpdateStatus mocks base method.
func (m *MockQuerier) UpdateStatus(ctx context.Context, arg sqlc.UpdateStatusParams) (sqlc.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockQuerierMockRecorder) UpdateStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateStatus), ctx, arg)
}

// UpdateUser mocks base method.
func (m *MockQuerier) UpdateUser(ctx context.Context, arg sqlc.UpdateUserParams) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockQuerierMockRecorder) UpdateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockQuerier)(nil).UpdateUser), ctx, arg)
}

// UpdateUserGoogleTokenAccess mocks base method.
func (m *MockQuerier) UpdateUserGoogleTokenAccess(ctx context.Context, arg sqlc.UpdateUserGoogleTokenAccessParams) (sqlc.UserGoogleToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGoogleTokenAccess", ctx, arg)
	ret0, _ := ret[0].(sqlc.UserGoogleToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserGoogleTokenAccess indicates an expected call of UpdateUserGoogleTokenAccess.
func (mr *MockQuerierMockRecorder) UpdateUserGoogleTokenAccess(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGoogleTokenAccess", reflect.TypeOf((*MockQuerier)(nil).UpdateUserGoogleTokenAccess), ctx, arg)
}

// UpsertUserGoogleToken mocks base method.
func (m *MockQuerier) UpsertUserGoogleToken(ctx context.Context, arg sqlc.UpsertUserGoogleTokenParams) (sqlc.UserGoogleToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserGoogleToken", ctx, arg)
	ret0, _ := ret[0].(sqlc.UserGoogleToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUserGoogleToken indicates an expected call of UpsertUserGoogleToken.
func (mr *MockQuerierMockRecorder) UpsertUserGoogleToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserGoogleToken", reflect.TypeOf((*MockQuerier)(nil).UpsertUserGoogleToken), ctx, arg)
}

// UpsertUserICalFeed mocks base method.
func (m *MockQuerier) UpsertUserICalFeed(ctx context.Context, arg sqlc.UpsertUserICalFeedParams) (sqlc.UserICalFeed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserICalFeed", ctx, arg)
	ret0, _ := ret[0].(sqlc.UserICalFeed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUserICalFeed indicates an expected call of UpsertUserICalFeed.
func (mr *MockQuerierMockRecorder) UpsertUserICalFeed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserICalFeed", reflect.TypeOf((*MockQuerier)(nil).UpsertUserICalFeed), ctx, arg)
}
